set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type")
set(LLVM_ENABLE_PROJECTS "clang" CACHE STRING "LLVM projects to build")
set(LLVM_TARGETS_TO_BUILD "" CACHE STRING "LLVM target architectures")
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "Include tests")
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "Include benchmarks")
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "Include examples")
set(LLVM_ENABLE_BINDINGS OFF CACHE BOOL "Enable bindings")
set(LLVM_ENABLE_ZLIB OFF CACHE BOOL "Zlib compression")
set(LLVM_ENABLE_ZSTD OFF CACHE BOOL "Zstd compression")
set(LLVM_ENABLE_TERMINFO OFF CACHE BOOL "Terminfo support")
